#!/bin/sh

[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME="$HOME/.local/share"
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_RUNTIME_DIR" ] && XDG_RUNTIME_DIR="$XDG_DATA_HOME"

export JAVA_HOME=/lib/jvm/openjdk17

cd /usr/share/cryptomator && "$JAVA_HOME/bin/java" \
	-p "mods" \
	-cp "lib/*" \
	-Dfile.encoding="utf-8" \
	-Dcryptomator.settingsPath="$XDG_CONFIG_HOME/Cryptomator/settings.json" \
	-Dcryptomator.logDir="$XDG_DATA_HOME/Cryptomator/logs" \
	-Dcryptomator.pluginDir="$XDG_DATA_HOME/Cryptomator/plugins" \
	-Dcryptomator.mountPointsDir="$XDG_DATA_HOME/Cryptomator/mnt" \
	-Dcryptomator.ipcSocketPath="$XDG_RUNTIME_DIR/Cryptomator/socket" \
	-Djdk.gtk.version=2 \
	-Xss5m \
	-Xmx256m \
	-m org.cryptomator.desktop/org.cryptomator.launcher.Cryptomator
